################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/IntelDecimal/bid128.c \
../Core/IntelDecimal/bid128_2_str_tables.c \
../Core/IntelDecimal/bid128_acos.c \
../Core/IntelDecimal/bid128_acosh.c \
../Core/IntelDecimal/bid128_add.c \
../Core/IntelDecimal/bid128_asin.c \
../Core/IntelDecimal/bid128_asinh.c \
../Core/IntelDecimal/bid128_atan.c \
../Core/IntelDecimal/bid128_atan2.c \
../Core/IntelDecimal/bid128_atanh.c \
../Core/IntelDecimal/bid128_cbrt.c \
../Core/IntelDecimal/bid128_compare.c \
../Core/IntelDecimal/bid128_cos.c \
../Core/IntelDecimal/bid128_cosh.c \
../Core/IntelDecimal/bid128_div.c \
../Core/IntelDecimal/bid128_erf.c \
../Core/IntelDecimal/bid128_erfc.c \
../Core/IntelDecimal/bid128_exp.c \
../Core/IntelDecimal/bid128_exp10.c \
../Core/IntelDecimal/bid128_exp2.c \
../Core/IntelDecimal/bid128_expm1.c \
../Core/IntelDecimal/bid128_fdimd.c \
../Core/IntelDecimal/bid128_fma.c \
../Core/IntelDecimal/bid128_fmod.c \
../Core/IntelDecimal/bid128_frexp.c \
../Core/IntelDecimal/bid128_hypot.c \
../Core/IntelDecimal/bid128_ldexp.c \
../Core/IntelDecimal/bid128_lgamma.c \
../Core/IntelDecimal/bid128_llrintd.c \
../Core/IntelDecimal/bid128_log.c \
../Core/IntelDecimal/bid128_log10.c \
../Core/IntelDecimal/bid128_log1p.c \
../Core/IntelDecimal/bid128_log2.c \
../Core/IntelDecimal/bid128_logb.c \
../Core/IntelDecimal/bid128_logbd.c \
../Core/IntelDecimal/bid128_lrintd.c \
../Core/IntelDecimal/bid128_lround.c \
../Core/IntelDecimal/bid128_minmax.c \
../Core/IntelDecimal/bid128_modf.c \
../Core/IntelDecimal/bid128_mul.c \
../Core/IntelDecimal/bid128_nearbyintd.c \
../Core/IntelDecimal/bid128_next.c \
../Core/IntelDecimal/bid128_nexttowardd.c \
../Core/IntelDecimal/bid128_noncomp.c \
../Core/IntelDecimal/bid128_pow.c \
../Core/IntelDecimal/bid128_quantexpd.c \
../Core/IntelDecimal/bid128_quantize.c \
../Core/IntelDecimal/bid128_rem.c \
../Core/IntelDecimal/bid128_round_integral.c \
../Core/IntelDecimal/bid128_scalb.c \
../Core/IntelDecimal/bid128_scalbl.c \
../Core/IntelDecimal/bid128_sin.c \
../Core/IntelDecimal/bid128_sinh.c \
../Core/IntelDecimal/bid128_sqrt.c \
../Core/IntelDecimal/bid128_string.c \
../Core/IntelDecimal/bid128_tan.c \
../Core/IntelDecimal/bid128_tanh.c \
../Core/IntelDecimal/bid128_tgamma.c \
../Core/IntelDecimal/bid128_to_int16.c \
../Core/IntelDecimal/bid128_to_int32.c \
../Core/IntelDecimal/bid128_to_int64.c \
../Core/IntelDecimal/bid128_to_int8.c \
../Core/IntelDecimal/bid128_to_uint16.c \
../Core/IntelDecimal/bid128_to_uint32.c \
../Core/IntelDecimal/bid128_to_uint64.c \
../Core/IntelDecimal/bid128_to_uint8.c \
../Core/IntelDecimal/bid32_acos.c \
../Core/IntelDecimal/bid32_acosh.c \
../Core/IntelDecimal/bid32_add.c \
../Core/IntelDecimal/bid32_asin.c \
../Core/IntelDecimal/bid32_asinh.c \
../Core/IntelDecimal/bid32_atan.c \
../Core/IntelDecimal/bid32_atan2.c \
../Core/IntelDecimal/bid32_atanh.c \
../Core/IntelDecimal/bid32_cbrt.c \
../Core/IntelDecimal/bid32_compare.c \
../Core/IntelDecimal/bid32_cos.c \
../Core/IntelDecimal/bid32_cosh.c \
../Core/IntelDecimal/bid32_div.c \
../Core/IntelDecimal/bid32_erf.c \
../Core/IntelDecimal/bid32_erfc.c \
../Core/IntelDecimal/bid32_exp.c \
../Core/IntelDecimal/bid32_exp10.c \
../Core/IntelDecimal/bid32_exp2.c \
../Core/IntelDecimal/bid32_expm1.c \
../Core/IntelDecimal/bid32_fdimd.c \
../Core/IntelDecimal/bid32_fma.c \
../Core/IntelDecimal/bid32_fmod.c \
../Core/IntelDecimal/bid32_frexp.c \
../Core/IntelDecimal/bid32_hypot.c \
../Core/IntelDecimal/bid32_ldexp.c \
../Core/IntelDecimal/bid32_lgamma.c \
../Core/IntelDecimal/bid32_llrintd.c \
../Core/IntelDecimal/bid32_log.c \
../Core/IntelDecimal/bid32_log10.c \
../Core/IntelDecimal/bid32_log1p.c \
../Core/IntelDecimal/bid32_log2.c \
../Core/IntelDecimal/bid32_logb.c \
../Core/IntelDecimal/bid32_logbd.c \
../Core/IntelDecimal/bid32_lrintd.c \
../Core/IntelDecimal/bid32_lround.c \
../Core/IntelDecimal/bid32_minmax.c \
../Core/IntelDecimal/bid32_modf.c \
../Core/IntelDecimal/bid32_mul.c \
../Core/IntelDecimal/bid32_nearbyintd.c \
../Core/IntelDecimal/bid32_next.c \
../Core/IntelDecimal/bid32_nexttowardd.c \
../Core/IntelDecimal/bid32_noncomp.c \
../Core/IntelDecimal/bid32_pow.c \
../Core/IntelDecimal/bid32_quantexpd.c \
../Core/IntelDecimal/bid32_quantize.c \
../Core/IntelDecimal/bid32_rem.c \
../Core/IntelDecimal/bid32_round_integral.c \
../Core/IntelDecimal/bid32_scalb.c \
../Core/IntelDecimal/bid32_scalbl.c \
../Core/IntelDecimal/bid32_sin.c \
../Core/IntelDecimal/bid32_sinh.c \
../Core/IntelDecimal/bid32_sqrt.c \
../Core/IntelDecimal/bid32_string.c \
../Core/IntelDecimal/bid32_sub.c \
../Core/IntelDecimal/bid32_tan.c \
../Core/IntelDecimal/bid32_tanh.c \
../Core/IntelDecimal/bid32_tgamma.c \
../Core/IntelDecimal/bid32_to_bid128.c \
../Core/IntelDecimal/bid32_to_bid64.c \
../Core/IntelDecimal/bid32_to_int16.c \
../Core/IntelDecimal/bid32_to_int32.c \
../Core/IntelDecimal/bid32_to_int64.c \
../Core/IntelDecimal/bid32_to_int8.c \
../Core/IntelDecimal/bid32_to_uint16.c \
../Core/IntelDecimal/bid32_to_uint32.c \
../Core/IntelDecimal/bid32_to_uint64.c \
../Core/IntelDecimal/bid32_to_uint8.c \
../Core/IntelDecimal/bid64_acos.c \
../Core/IntelDecimal/bid64_acosh.c \
../Core/IntelDecimal/bid64_add.c \
../Core/IntelDecimal/bid64_asin.c \
../Core/IntelDecimal/bid64_asinh.c \
../Core/IntelDecimal/bid64_atan.c \
../Core/IntelDecimal/bid64_atan2.c \
../Core/IntelDecimal/bid64_atanh.c \
../Core/IntelDecimal/bid64_cbrt.c \
../Core/IntelDecimal/bid64_compare.c \
../Core/IntelDecimal/bid64_cos.c \
../Core/IntelDecimal/bid64_cosh.c \
../Core/IntelDecimal/bid64_div.c \
../Core/IntelDecimal/bid64_erf.c \
../Core/IntelDecimal/bid64_erfc.c \
../Core/IntelDecimal/bid64_exp.c \
../Core/IntelDecimal/bid64_exp10.c \
../Core/IntelDecimal/bid64_exp2.c \
../Core/IntelDecimal/bid64_expm1.c \
../Core/IntelDecimal/bid64_fdimd.c \
../Core/IntelDecimal/bid64_fma.c \
../Core/IntelDecimal/bid64_fmod.c \
../Core/IntelDecimal/bid64_frexp.c \
../Core/IntelDecimal/bid64_hypot.c \
../Core/IntelDecimal/bid64_ldexp.c \
../Core/IntelDecimal/bid64_lgamma.c \
../Core/IntelDecimal/bid64_llrintd.c \
../Core/IntelDecimal/bid64_log.c \
../Core/IntelDecimal/bid64_log10.c \
../Core/IntelDecimal/bid64_log1p.c \
../Core/IntelDecimal/bid64_log2.c \
../Core/IntelDecimal/bid64_logb.c \
../Core/IntelDecimal/bid64_logbd.c \
../Core/IntelDecimal/bid64_lrintd.c \
../Core/IntelDecimal/bid64_lround.c \
../Core/IntelDecimal/bid64_minmax.c \
../Core/IntelDecimal/bid64_modf.c \
../Core/IntelDecimal/bid64_mul.c \
../Core/IntelDecimal/bid64_nearbyintd.c \
../Core/IntelDecimal/bid64_next.c \
../Core/IntelDecimal/bid64_nexttowardd.c \
../Core/IntelDecimal/bid64_noncomp.c \
../Core/IntelDecimal/bid64_pow.c \
../Core/IntelDecimal/bid64_quantexpd.c \
../Core/IntelDecimal/bid64_quantize.c \
../Core/IntelDecimal/bid64_rem.c \
../Core/IntelDecimal/bid64_round_integral.c \
../Core/IntelDecimal/bid64_scalb.c \
../Core/IntelDecimal/bid64_scalbl.c \
../Core/IntelDecimal/bid64_sin.c \
../Core/IntelDecimal/bid64_sinh.c \
../Core/IntelDecimal/bid64_sqrt.c \
../Core/IntelDecimal/bid64_string.c \
../Core/IntelDecimal/bid64_tan.c \
../Core/IntelDecimal/bid64_tanh.c \
../Core/IntelDecimal/bid64_tgamma.c \
../Core/IntelDecimal/bid64_to_bid128.c \
../Core/IntelDecimal/bid64_to_int16.c \
../Core/IntelDecimal/bid64_to_int32.c \
../Core/IntelDecimal/bid64_to_int64.c \
../Core/IntelDecimal/bid64_to_int8.c \
../Core/IntelDecimal/bid64_to_uint16.c \
../Core/IntelDecimal/bid64_to_uint32.c \
../Core/IntelDecimal/bid64_to_uint64.c \
../Core/IntelDecimal/bid64_to_uint8.c \
../Core/IntelDecimal/bid_binarydecimal.c \
../Core/IntelDecimal/bid_convert_data.c \
../Core/IntelDecimal/bid_decimal_data.c \
../Core/IntelDecimal/bid_decimal_globals.c \
../Core/IntelDecimal/bid_dpd.c \
../Core/IntelDecimal/bid_feclearexcept.c \
../Core/IntelDecimal/bid_fegetexceptflag.c \
../Core/IntelDecimal/bid_feraiseexcept.c \
../Core/IntelDecimal/bid_fesetexceptflag.c \
../Core/IntelDecimal/bid_fetestexcept.c \
../Core/IntelDecimal/bid_flag_operations.c \
../Core/IntelDecimal/bid_from_int.c \
../Core/IntelDecimal/bid_round.c \
../Core/IntelDecimal/strtod128.c \
../Core/IntelDecimal/strtod32.c \
../Core/IntelDecimal/strtod64.c \
../Core/IntelDecimal/wcstod128.c \
../Core/IntelDecimal/wcstod32.c \
../Core/IntelDecimal/wcstod64.c 

C_DEPS += \
./Core/IntelDecimal/bid128.d \
./Core/IntelDecimal/bid128_2_str_tables.d \
./Core/IntelDecimal/bid128_acos.d \
./Core/IntelDecimal/bid128_acosh.d \
./Core/IntelDecimal/bid128_add.d \
./Core/IntelDecimal/bid128_asin.d \
./Core/IntelDecimal/bid128_asinh.d \
./Core/IntelDecimal/bid128_atan.d \
./Core/IntelDecimal/bid128_atan2.d \
./Core/IntelDecimal/bid128_atanh.d \
./Core/IntelDecimal/bid128_cbrt.d \
./Core/IntelDecimal/bid128_compare.d \
./Core/IntelDecimal/bid128_cos.d \
./Core/IntelDecimal/bid128_cosh.d \
./Core/IntelDecimal/bid128_div.d \
./Core/IntelDecimal/bid128_erf.d \
./Core/IntelDecimal/bid128_erfc.d \
./Core/IntelDecimal/bid128_exp.d \
./Core/IntelDecimal/bid128_exp10.d \
./Core/IntelDecimal/bid128_exp2.d \
./Core/IntelDecimal/bid128_expm1.d \
./Core/IntelDecimal/bid128_fdimd.d \
./Core/IntelDecimal/bid128_fma.d \
./Core/IntelDecimal/bid128_fmod.d \
./Core/IntelDecimal/bid128_frexp.d \
./Core/IntelDecimal/bid128_hypot.d \
./Core/IntelDecimal/bid128_ldexp.d \
./Core/IntelDecimal/bid128_lgamma.d \
./Core/IntelDecimal/bid128_llrintd.d \
./Core/IntelDecimal/bid128_log.d \
./Core/IntelDecimal/bid128_log10.d \
./Core/IntelDecimal/bid128_log1p.d \
./Core/IntelDecimal/bid128_log2.d \
./Core/IntelDecimal/bid128_logb.d \
./Core/IntelDecimal/bid128_logbd.d \
./Core/IntelDecimal/bid128_lrintd.d \
./Core/IntelDecimal/bid128_lround.d \
./Core/IntelDecimal/bid128_minmax.d \
./Core/IntelDecimal/bid128_modf.d \
./Core/IntelDecimal/bid128_mul.d \
./Core/IntelDecimal/bid128_nearbyintd.d \
./Core/IntelDecimal/bid128_next.d \
./Core/IntelDecimal/bid128_nexttowardd.d \
./Core/IntelDecimal/bid128_noncomp.d \
./Core/IntelDecimal/bid128_pow.d \
./Core/IntelDecimal/bid128_quantexpd.d \
./Core/IntelDecimal/bid128_quantize.d \
./Core/IntelDecimal/bid128_rem.d \
./Core/IntelDecimal/bid128_round_integral.d \
./Core/IntelDecimal/bid128_scalb.d \
./Core/IntelDecimal/bid128_scalbl.d \
./Core/IntelDecimal/bid128_sin.d \
./Core/IntelDecimal/bid128_sinh.d \
./Core/IntelDecimal/bid128_sqrt.d \
./Core/IntelDecimal/bid128_string.d \
./Core/IntelDecimal/bid128_tan.d \
./Core/IntelDecimal/bid128_tanh.d \
./Core/IntelDecimal/bid128_tgamma.d \
./Core/IntelDecimal/bid128_to_int16.d \
./Core/IntelDecimal/bid128_to_int32.d \
./Core/IntelDecimal/bid128_to_int64.d \
./Core/IntelDecimal/bid128_to_int8.d \
./Core/IntelDecimal/bid128_to_uint16.d \
./Core/IntelDecimal/bid128_to_uint32.d \
./Core/IntelDecimal/bid128_to_uint64.d \
./Core/IntelDecimal/bid128_to_uint8.d \
./Core/IntelDecimal/bid32_acos.d \
./Core/IntelDecimal/bid32_acosh.d \
./Core/IntelDecimal/bid32_add.d \
./Core/IntelDecimal/bid32_asin.d \
./Core/IntelDecimal/bid32_asinh.d \
./Core/IntelDecimal/bid32_atan.d \
./Core/IntelDecimal/bid32_atan2.d \
./Core/IntelDecimal/bid32_atanh.d \
./Core/IntelDecimal/bid32_cbrt.d \
./Core/IntelDecimal/bid32_compare.d \
./Core/IntelDecimal/bid32_cos.d \
./Core/IntelDecimal/bid32_cosh.d \
./Core/IntelDecimal/bid32_div.d \
./Core/IntelDecimal/bid32_erf.d \
./Core/IntelDecimal/bid32_erfc.d \
./Core/IntelDecimal/bid32_exp.d \
./Core/IntelDecimal/bid32_exp10.d \
./Core/IntelDecimal/bid32_exp2.d \
./Core/IntelDecimal/bid32_expm1.d \
./Core/IntelDecimal/bid32_fdimd.d \
./Core/IntelDecimal/bid32_fma.d \
./Core/IntelDecimal/bid32_fmod.d \
./Core/IntelDecimal/bid32_frexp.d \
./Core/IntelDecimal/bid32_hypot.d \
./Core/IntelDecimal/bid32_ldexp.d \
./Core/IntelDecimal/bid32_lgamma.d \
./Core/IntelDecimal/bid32_llrintd.d \
./Core/IntelDecimal/bid32_log.d \
./Core/IntelDecimal/bid32_log10.d \
./Core/IntelDecimal/bid32_log1p.d \
./Core/IntelDecimal/bid32_log2.d \
./Core/IntelDecimal/bid32_logb.d \
./Core/IntelDecimal/bid32_logbd.d \
./Core/IntelDecimal/bid32_lrintd.d \
./Core/IntelDecimal/bid32_lround.d \
./Core/IntelDecimal/bid32_minmax.d \
./Core/IntelDecimal/bid32_modf.d \
./Core/IntelDecimal/bid32_mul.d \
./Core/IntelDecimal/bid32_nearbyintd.d \
./Core/IntelDecimal/bid32_next.d \
./Core/IntelDecimal/bid32_nexttowardd.d \
./Core/IntelDecimal/bid32_noncomp.d \
./Core/IntelDecimal/bid32_pow.d \
./Core/IntelDecimal/bid32_quantexpd.d \
./Core/IntelDecimal/bid32_quantize.d \
./Core/IntelDecimal/bid32_rem.d \
./Core/IntelDecimal/bid32_round_integral.d \
./Core/IntelDecimal/bid32_scalb.d \
./Core/IntelDecimal/bid32_scalbl.d \
./Core/IntelDecimal/bid32_sin.d \
./Core/IntelDecimal/bid32_sinh.d \
./Core/IntelDecimal/bid32_sqrt.d \
./Core/IntelDecimal/bid32_string.d \
./Core/IntelDecimal/bid32_sub.d \
./Core/IntelDecimal/bid32_tan.d \
./Core/IntelDecimal/bid32_tanh.d \
./Core/IntelDecimal/bid32_tgamma.d \
./Core/IntelDecimal/bid32_to_bid128.d \
./Core/IntelDecimal/bid32_to_bid64.d \
./Core/IntelDecimal/bid32_to_int16.d \
./Core/IntelDecimal/bid32_to_int32.d \
./Core/IntelDecimal/bid32_to_int64.d \
./Core/IntelDecimal/bid32_to_int8.d \
./Core/IntelDecimal/bid32_to_uint16.d \
./Core/IntelDecimal/bid32_to_uint32.d \
./Core/IntelDecimal/bid32_to_uint64.d \
./Core/IntelDecimal/bid32_to_uint8.d \
./Core/IntelDecimal/bid64_acos.d \
./Core/IntelDecimal/bid64_acosh.d \
./Core/IntelDecimal/bid64_add.d \
./Core/IntelDecimal/bid64_asin.d \
./Core/IntelDecimal/bid64_asinh.d \
./Core/IntelDecimal/bid64_atan.d \
./Core/IntelDecimal/bid64_atan2.d \
./Core/IntelDecimal/bid64_atanh.d \
./Core/IntelDecimal/bid64_cbrt.d \
./Core/IntelDecimal/bid64_compare.d \
./Core/IntelDecimal/bid64_cos.d \
./Core/IntelDecimal/bid64_cosh.d \
./Core/IntelDecimal/bid64_div.d \
./Core/IntelDecimal/bid64_erf.d \
./Core/IntelDecimal/bid64_erfc.d \
./Core/IntelDecimal/bid64_exp.d \
./Core/IntelDecimal/bid64_exp10.d \
./Core/IntelDecimal/bid64_exp2.d \
./Core/IntelDecimal/bid64_expm1.d \
./Core/IntelDecimal/bid64_fdimd.d \
./Core/IntelDecimal/bid64_fma.d \
./Core/IntelDecimal/bid64_fmod.d \
./Core/IntelDecimal/bid64_frexp.d \
./Core/IntelDecimal/bid64_hypot.d \
./Core/IntelDecimal/bid64_ldexp.d \
./Core/IntelDecimal/bid64_lgamma.d \
./Core/IntelDecimal/bid64_llrintd.d \
./Core/IntelDecimal/bid64_log.d \
./Core/IntelDecimal/bid64_log10.d \
./Core/IntelDecimal/bid64_log1p.d \
./Core/IntelDecimal/bid64_log2.d \
./Core/IntelDecimal/bid64_logb.d \
./Core/IntelDecimal/bid64_logbd.d \
./Core/IntelDecimal/bid64_lrintd.d \
./Core/IntelDecimal/bid64_lround.d \
./Core/IntelDecimal/bid64_minmax.d \
./Core/IntelDecimal/bid64_modf.d \
./Core/IntelDecimal/bid64_mul.d \
./Core/IntelDecimal/bid64_nearbyintd.d \
./Core/IntelDecimal/bid64_next.d \
./Core/IntelDecimal/bid64_nexttowardd.d \
./Core/IntelDecimal/bid64_noncomp.d \
./Core/IntelDecimal/bid64_pow.d \
./Core/IntelDecimal/bid64_quantexpd.d \
./Core/IntelDecimal/bid64_quantize.d \
./Core/IntelDecimal/bid64_rem.d \
./Core/IntelDecimal/bid64_round_integral.d \
./Core/IntelDecimal/bid64_scalb.d \
./Core/IntelDecimal/bid64_scalbl.d \
./Core/IntelDecimal/bid64_sin.d \
./Core/IntelDecimal/bid64_sinh.d \
./Core/IntelDecimal/bid64_sqrt.d \
./Core/IntelDecimal/bid64_string.d \
./Core/IntelDecimal/bid64_tan.d \
./Core/IntelDecimal/bid64_tanh.d \
./Core/IntelDecimal/bid64_tgamma.d \
./Core/IntelDecimal/bid64_to_bid128.d \
./Core/IntelDecimal/bid64_to_int16.d \
./Core/IntelDecimal/bid64_to_int32.d \
./Core/IntelDecimal/bid64_to_int64.d \
./Core/IntelDecimal/bid64_to_int8.d \
./Core/IntelDecimal/bid64_to_uint16.d \
./Core/IntelDecimal/bid64_to_uint32.d \
./Core/IntelDecimal/bid64_to_uint64.d \
./Core/IntelDecimal/bid64_to_uint8.d \
./Core/IntelDecimal/bid_binarydecimal.d \
./Core/IntelDecimal/bid_convert_data.d \
./Core/IntelDecimal/bid_decimal_data.d \
./Core/IntelDecimal/bid_decimal_globals.d \
./Core/IntelDecimal/bid_dpd.d \
./Core/IntelDecimal/bid_feclearexcept.d \
./Core/IntelDecimal/bid_fegetexceptflag.d \
./Core/IntelDecimal/bid_feraiseexcept.d \
./Core/IntelDecimal/bid_fesetexceptflag.d \
./Core/IntelDecimal/bid_fetestexcept.d \
./Core/IntelDecimal/bid_flag_operations.d \
./Core/IntelDecimal/bid_from_int.d \
./Core/IntelDecimal/bid_round.d \
./Core/IntelDecimal/strtod128.d \
./Core/IntelDecimal/strtod32.d \
./Core/IntelDecimal/strtod64.d \
./Core/IntelDecimal/wcstod128.d \
./Core/IntelDecimal/wcstod32.d \
./Core/IntelDecimal/wcstod64.d 

OBJS += \
./Core/IntelDecimal/bid128.o \
./Core/IntelDecimal/bid128_2_str_tables.o \
./Core/IntelDecimal/bid128_acos.o \
./Core/IntelDecimal/bid128_acosh.o \
./Core/IntelDecimal/bid128_add.o \
./Core/IntelDecimal/bid128_asin.o \
./Core/IntelDecimal/bid128_asinh.o \
./Core/IntelDecimal/bid128_atan.o \
./Core/IntelDecimal/bid128_atan2.o \
./Core/IntelDecimal/bid128_atanh.o \
./Core/IntelDecimal/bid128_cbrt.o \
./Core/IntelDecimal/bid128_compare.o \
./Core/IntelDecimal/bid128_cos.o \
./Core/IntelDecimal/bid128_cosh.o \
./Core/IntelDecimal/bid128_div.o \
./Core/IntelDecimal/bid128_erf.o \
./Core/IntelDecimal/bid128_erfc.o \
./Core/IntelDecimal/bid128_exp.o \
./Core/IntelDecimal/bid128_exp10.o \
./Core/IntelDecimal/bid128_exp2.o \
./Core/IntelDecimal/bid128_expm1.o \
./Core/IntelDecimal/bid128_fdimd.o \
./Core/IntelDecimal/bid128_fma.o \
./Core/IntelDecimal/bid128_fmod.o \
./Core/IntelDecimal/bid128_frexp.o \
./Core/IntelDecimal/bid128_hypot.o \
./Core/IntelDecimal/bid128_ldexp.o \
./Core/IntelDecimal/bid128_lgamma.o \
./Core/IntelDecimal/bid128_llrintd.o \
./Core/IntelDecimal/bid128_log.o \
./Core/IntelDecimal/bid128_log10.o \
./Core/IntelDecimal/bid128_log1p.o \
./Core/IntelDecimal/bid128_log2.o \
./Core/IntelDecimal/bid128_logb.o \
./Core/IntelDecimal/bid128_logbd.o \
./Core/IntelDecimal/bid128_lrintd.o \
./Core/IntelDecimal/bid128_lround.o \
./Core/IntelDecimal/bid128_minmax.o \
./Core/IntelDecimal/bid128_modf.o \
./Core/IntelDecimal/bid128_mul.o \
./Core/IntelDecimal/bid128_nearbyintd.o \
./Core/IntelDecimal/bid128_next.o \
./Core/IntelDecimal/bid128_nexttowardd.o \
./Core/IntelDecimal/bid128_noncomp.o \
./Core/IntelDecimal/bid128_pow.o \
./Core/IntelDecimal/bid128_quantexpd.o \
./Core/IntelDecimal/bid128_quantize.o \
./Core/IntelDecimal/bid128_rem.o \
./Core/IntelDecimal/bid128_round_integral.o \
./Core/IntelDecimal/bid128_scalb.o \
./Core/IntelDecimal/bid128_scalbl.o \
./Core/IntelDecimal/bid128_sin.o \
./Core/IntelDecimal/bid128_sinh.o \
./Core/IntelDecimal/bid128_sqrt.o \
./Core/IntelDecimal/bid128_string.o \
./Core/IntelDecimal/bid128_tan.o \
./Core/IntelDecimal/bid128_tanh.o \
./Core/IntelDecimal/bid128_tgamma.o \
./Core/IntelDecimal/bid128_to_int16.o \
./Core/IntelDecimal/bid128_to_int32.o \
./Core/IntelDecimal/bid128_to_int64.o \
./Core/IntelDecimal/bid128_to_int8.o \
./Core/IntelDecimal/bid128_to_uint16.o \
./Core/IntelDecimal/bid128_to_uint32.o \
./Core/IntelDecimal/bid128_to_uint64.o \
./Core/IntelDecimal/bid128_to_uint8.o \
./Core/IntelDecimal/bid32_acos.o \
./Core/IntelDecimal/bid32_acosh.o \
./Core/IntelDecimal/bid32_add.o \
./Core/IntelDecimal/bid32_asin.o \
./Core/IntelDecimal/bid32_asinh.o \
./Core/IntelDecimal/bid32_atan.o \
./Core/IntelDecimal/bid32_atan2.o \
./Core/IntelDecimal/bid32_atanh.o \
./Core/IntelDecimal/bid32_cbrt.o \
./Core/IntelDecimal/bid32_compare.o \
./Core/IntelDecimal/bid32_cos.o \
./Core/IntelDecimal/bid32_cosh.o \
./Core/IntelDecimal/bid32_div.o \
./Core/IntelDecimal/bid32_erf.o \
./Core/IntelDecimal/bid32_erfc.o \
./Core/IntelDecimal/bid32_exp.o \
./Core/IntelDecimal/bid32_exp10.o \
./Core/IntelDecimal/bid32_exp2.o \
./Core/IntelDecimal/bid32_expm1.o \
./Core/IntelDecimal/bid32_fdimd.o \
./Core/IntelDecimal/bid32_fma.o \
./Core/IntelDecimal/bid32_fmod.o \
./Core/IntelDecimal/bid32_frexp.o \
./Core/IntelDecimal/bid32_hypot.o \
./Core/IntelDecimal/bid32_ldexp.o \
./Core/IntelDecimal/bid32_lgamma.o \
./Core/IntelDecimal/bid32_llrintd.o \
./Core/IntelDecimal/bid32_log.o \
./Core/IntelDecimal/bid32_log10.o \
./Core/IntelDecimal/bid32_log1p.o \
./Core/IntelDecimal/bid32_log2.o \
./Core/IntelDecimal/bid32_logb.o \
./Core/IntelDecimal/bid32_logbd.o \
./Core/IntelDecimal/bid32_lrintd.o \
./Core/IntelDecimal/bid32_lround.o \
./Core/IntelDecimal/bid32_minmax.o \
./Core/IntelDecimal/bid32_modf.o \
./Core/IntelDecimal/bid32_mul.o \
./Core/IntelDecimal/bid32_nearbyintd.o \
./Core/IntelDecimal/bid32_next.o \
./Core/IntelDecimal/bid32_nexttowardd.o \
./Core/IntelDecimal/bid32_noncomp.o \
./Core/IntelDecimal/bid32_pow.o \
./Core/IntelDecimal/bid32_quantexpd.o \
./Core/IntelDecimal/bid32_quantize.o \
./Core/IntelDecimal/bid32_rem.o \
./Core/IntelDecimal/bid32_round_integral.o \
./Core/IntelDecimal/bid32_scalb.o \
./Core/IntelDecimal/bid32_scalbl.o \
./Core/IntelDecimal/bid32_sin.o \
./Core/IntelDecimal/bid32_sinh.o \
./Core/IntelDecimal/bid32_sqrt.o \
./Core/IntelDecimal/bid32_string.o \
./Core/IntelDecimal/bid32_sub.o \
./Core/IntelDecimal/bid32_tan.o \
./Core/IntelDecimal/bid32_tanh.o \
./Core/IntelDecimal/bid32_tgamma.o \
./Core/IntelDecimal/bid32_to_bid128.o \
./Core/IntelDecimal/bid32_to_bid64.o \
./Core/IntelDecimal/bid32_to_int16.o \
./Core/IntelDecimal/bid32_to_int32.o \
./Core/IntelDecimal/bid32_to_int64.o \
./Core/IntelDecimal/bid32_to_int8.o \
./Core/IntelDecimal/bid32_to_uint16.o \
./Core/IntelDecimal/bid32_to_uint32.o \
./Core/IntelDecimal/bid32_to_uint64.o \
./Core/IntelDecimal/bid32_to_uint8.o \
./Core/IntelDecimal/bid64_acos.o \
./Core/IntelDecimal/bid64_acosh.o \
./Core/IntelDecimal/bid64_add.o \
./Core/IntelDecimal/bid64_asin.o \
./Core/IntelDecimal/bid64_asinh.o \
./Core/IntelDecimal/bid64_atan.o \
./Core/IntelDecimal/bid64_atan2.o \
./Core/IntelDecimal/bid64_atanh.o \
./Core/IntelDecimal/bid64_cbrt.o \
./Core/IntelDecimal/bid64_compare.o \
./Core/IntelDecimal/bid64_cos.o \
./Core/IntelDecimal/bid64_cosh.o \
./Core/IntelDecimal/bid64_div.o \
./Core/IntelDecimal/bid64_erf.o \
./Core/IntelDecimal/bid64_erfc.o \
./Core/IntelDecimal/bid64_exp.o \
./Core/IntelDecimal/bid64_exp10.o \
./Core/IntelDecimal/bid64_exp2.o \
./Core/IntelDecimal/bid64_expm1.o \
./Core/IntelDecimal/bid64_fdimd.o \
./Core/IntelDecimal/bid64_fma.o \
./Core/IntelDecimal/bid64_fmod.o \
./Core/IntelDecimal/bid64_frexp.o \
./Core/IntelDecimal/bid64_hypot.o \
./Core/IntelDecimal/bid64_ldexp.o \
./Core/IntelDecimal/bid64_lgamma.o \
./Core/IntelDecimal/bid64_llrintd.o \
./Core/IntelDecimal/bid64_log.o \
./Core/IntelDecimal/bid64_log10.o \
./Core/IntelDecimal/bid64_log1p.o \
./Core/IntelDecimal/bid64_log2.o \
./Core/IntelDecimal/bid64_logb.o \
./Core/IntelDecimal/bid64_logbd.o \
./Core/IntelDecimal/bid64_lrintd.o \
./Core/IntelDecimal/bid64_lround.o \
./Core/IntelDecimal/bid64_minmax.o \
./Core/IntelDecimal/bid64_modf.o \
./Core/IntelDecimal/bid64_mul.o \
./Core/IntelDecimal/bid64_nearbyintd.o \
./Core/IntelDecimal/bid64_next.o \
./Core/IntelDecimal/bid64_nexttowardd.o \
./Core/IntelDecimal/bid64_noncomp.o \
./Core/IntelDecimal/bid64_pow.o \
./Core/IntelDecimal/bid64_quantexpd.o \
./Core/IntelDecimal/bid64_quantize.o \
./Core/IntelDecimal/bid64_rem.o \
./Core/IntelDecimal/bid64_round_integral.o \
./Core/IntelDecimal/bid64_scalb.o \
./Core/IntelDecimal/bid64_scalbl.o \
./Core/IntelDecimal/bid64_sin.o \
./Core/IntelDecimal/bid64_sinh.o \
./Core/IntelDecimal/bid64_sqrt.o \
./Core/IntelDecimal/bid64_string.o \
./Core/IntelDecimal/bid64_tan.o \
./Core/IntelDecimal/bid64_tanh.o \
./Core/IntelDecimal/bid64_tgamma.o \
./Core/IntelDecimal/bid64_to_bid128.o \
./Core/IntelDecimal/bid64_to_int16.o \
./Core/IntelDecimal/bid64_to_int32.o \
./Core/IntelDecimal/bid64_to_int64.o \
./Core/IntelDecimal/bid64_to_int8.o \
./Core/IntelDecimal/bid64_to_uint16.o \
./Core/IntelDecimal/bid64_to_uint32.o \
./Core/IntelDecimal/bid64_to_uint64.o \
./Core/IntelDecimal/bid64_to_uint8.o \
./Core/IntelDecimal/bid_binarydecimal.o \
./Core/IntelDecimal/bid_convert_data.o \
./Core/IntelDecimal/bid_decimal_data.o \
./Core/IntelDecimal/bid_decimal_globals.o \
./Core/IntelDecimal/bid_dpd.o \
./Core/IntelDecimal/bid_feclearexcept.o \
./Core/IntelDecimal/bid_fegetexceptflag.o \
./Core/IntelDecimal/bid_feraiseexcept.o \
./Core/IntelDecimal/bid_fesetexceptflag.o \
./Core/IntelDecimal/bid_fetestexcept.o \
./Core/IntelDecimal/bid_flag_operations.o \
./Core/IntelDecimal/bid_from_int.o \
./Core/IntelDecimal/bid_round.o \
./Core/IntelDecimal/strtod128.o \
./Core/IntelDecimal/strtod32.o \
./Core/IntelDecimal/strtod64.o \
./Core/IntelDecimal/wcstod128.o \
./Core/IntelDecimal/wcstod32.o \
./Core/IntelDecimal/wcstod64.o 


# Each subdirectory must supply rules for building sources it contributes
Core/IntelDecimal/%.o Core/IntelDecimal/%.su Core/IntelDecimal/%.cyclo: ../Core/IntelDecimal/%.c Core/IntelDecimal/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L475xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Jerem/OneDrive/Documents/career/my_projects/stm-workspace/Free42/Core/Inc/IntelDecimal" -I"C:/Users/Jerem/OneDrive/Documents/career/my_projects/stm-workspace/Free42/Core/Inc/Free42" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-IntelDecimal

clean-Core-2f-IntelDecimal:
	-$(RM) ./Core/IntelDecimal/bid128.cyclo ./Core/IntelDecimal/bid128.d ./Core/IntelDecimal/bid128.o ./Core/IntelDecimal/bid128.su ./Core/IntelDecimal/bid128_2_str_tables.cyclo ./Core/IntelDecimal/bid128_2_str_tables.d ./Core/IntelDecimal/bid128_2_str_tables.o ./Core/IntelDecimal/bid128_2_str_tables.su ./Core/IntelDecimal/bid128_acos.cyclo ./Core/IntelDecimal/bid128_acos.d ./Core/IntelDecimal/bid128_acos.o ./Core/IntelDecimal/bid128_acos.su ./Core/IntelDecimal/bid128_acosh.cyclo ./Core/IntelDecimal/bid128_acosh.d ./Core/IntelDecimal/bid128_acosh.o ./Core/IntelDecimal/bid128_acosh.su ./Core/IntelDecimal/bid128_add.cyclo ./Core/IntelDecimal/bid128_add.d ./Core/IntelDecimal/bid128_add.o ./Core/IntelDecimal/bid128_add.su ./Core/IntelDecimal/bid128_asin.cyclo ./Core/IntelDecimal/bid128_asin.d ./Core/IntelDecimal/bid128_asin.o ./Core/IntelDecimal/bid128_asin.su ./Core/IntelDecimal/bid128_asinh.cyclo ./Core/IntelDecimal/bid128_asinh.d ./Core/IntelDecimal/bid128_asinh.o ./Core/IntelDecimal/bid128_asinh.su ./Core/IntelDecimal/bid128_atan.cyclo ./Core/IntelDecimal/bid128_atan.d ./Core/IntelDecimal/bid128_atan.o ./Core/IntelDecimal/bid128_atan.su ./Core/IntelDecimal/bid128_atan2.cyclo ./Core/IntelDecimal/bid128_atan2.d ./Core/IntelDecimal/bid128_atan2.o ./Core/IntelDecimal/bid128_atan2.su ./Core/IntelDecimal/bid128_atanh.cyclo ./Core/IntelDecimal/bid128_atanh.d ./Core/IntelDecimal/bid128_atanh.o ./Core/IntelDecimal/bid128_atanh.su ./Core/IntelDecimal/bid128_cbrt.cyclo ./Core/IntelDecimal/bid128_cbrt.d ./Core/IntelDecimal/bid128_cbrt.o ./Core/IntelDecimal/bid128_cbrt.su ./Core/IntelDecimal/bid128_compare.cyclo ./Core/IntelDecimal/bid128_compare.d ./Core/IntelDecimal/bid128_compare.o ./Core/IntelDecimal/bid128_compare.su ./Core/IntelDecimal/bid128_cos.cyclo ./Core/IntelDecimal/bid128_cos.d ./Core/IntelDecimal/bid128_cos.o ./Core/IntelDecimal/bid128_cos.su ./Core/IntelDecimal/bid128_cosh.cyclo ./Core/IntelDecimal/bid128_cosh.d ./Core/IntelDecimal/bid128_cosh.o ./Core/IntelDecimal/bid128_cosh.su ./Core/IntelDecimal/bid128_div.cyclo ./Core/IntelDecimal/bid128_div.d ./Core/IntelDecimal/bid128_div.o ./Core/IntelDecimal/bid128_div.su ./Core/IntelDecimal/bid128_erf.cyclo ./Core/IntelDecimal/bid128_erf.d ./Core/IntelDecimal/bid128_erf.o ./Core/IntelDecimal/bid128_erf.su ./Core/IntelDecimal/bid128_erfc.cyclo ./Core/IntelDecimal/bid128_erfc.d ./Core/IntelDecimal/bid128_erfc.o ./Core/IntelDecimal/bid128_erfc.su ./Core/IntelDecimal/bid128_exp.cyclo ./Core/IntelDecimal/bid128_exp.d ./Core/IntelDecimal/bid128_exp.o ./Core/IntelDecimal/bid128_exp.su ./Core/IntelDecimal/bid128_exp10.cyclo ./Core/IntelDecimal/bid128_exp10.d ./Core/IntelDecimal/bid128_exp10.o ./Core/IntelDecimal/bid128_exp10.su ./Core/IntelDecimal/bid128_exp2.cyclo ./Core/IntelDecimal/bid128_exp2.d ./Core/IntelDecimal/bid128_exp2.o ./Core/IntelDecimal/bid128_exp2.su ./Core/IntelDecimal/bid128_expm1.cyclo ./Core/IntelDecimal/bid128_expm1.d ./Core/IntelDecimal/bid128_expm1.o ./Core/IntelDecimal/bid128_expm1.su ./Core/IntelDecimal/bid128_fdimd.cyclo ./Core/IntelDecimal/bid128_fdimd.d ./Core/IntelDecimal/bid128_fdimd.o ./Core/IntelDecimal/bid128_fdimd.su ./Core/IntelDecimal/bid128_fma.cyclo ./Core/IntelDecimal/bid128_fma.d ./Core/IntelDecimal/bid128_fma.o ./Core/IntelDecimal/bid128_fma.su ./Core/IntelDecimal/bid128_fmod.cyclo ./Core/IntelDecimal/bid128_fmod.d ./Core/IntelDecimal/bid128_fmod.o ./Core/IntelDecimal/bid128_fmod.su ./Core/IntelDecimal/bid128_frexp.cyclo ./Core/IntelDecimal/bid128_frexp.d ./Core/IntelDecimal/bid128_frexp.o ./Core/IntelDecimal/bid128_frexp.su ./Core/IntelDecimal/bid128_hypot.cyclo ./Core/IntelDecimal/bid128_hypot.d ./Core/IntelDecimal/bid128_hypot.o ./Core/IntelDecimal/bid128_hypot.su ./Core/IntelDecimal/bid128_ldexp.cyclo ./Core/IntelDecimal/bid128_ldexp.d ./Core/IntelDecimal/bid128_ldexp.o ./Core/IntelDecimal/bid128_ldexp.su ./Core/IntelDecimal/bid128_lgamma.cyclo ./Core/IntelDecimal/bid128_lgamma.d ./Core/IntelDecimal/bid128_lgamma.o ./Core/IntelDecimal/bid128_lgamma.su ./Core/IntelDecimal/bid128_llrintd.cyclo ./Core/IntelDecimal/bid128_llrintd.d ./Core/IntelDecimal/bid128_llrintd.o ./Core/IntelDecimal/bid128_llrintd.su ./Core/IntelDecimal/bid128_log.cyclo ./Core/IntelDecimal/bid128_log.d ./Core/IntelDecimal/bid128_log.o ./Core/IntelDecimal/bid128_log.su ./Core/IntelDecimal/bid128_log10.cyclo ./Core/IntelDecimal/bid128_log10.d ./Core/IntelDecimal/bid128_log10.o ./Core/IntelDecimal/bid128_log10.su ./Core/IntelDecimal/bid128_log1p.cyclo ./Core/IntelDecimal/bid128_log1p.d ./Core/IntelDecimal/bid128_log1p.o ./Core/IntelDecimal/bid128_log1p.su ./Core/IntelDecimal/bid128_log2.cyclo ./Core/IntelDecimal/bid128_log2.d ./Core/IntelDecimal/bid128_log2.o ./Core/IntelDecimal/bid128_log2.su ./Core/IntelDecimal/bid128_logb.cyclo ./Core/IntelDecimal/bid128_logb.d ./Core/IntelDecimal/bid128_logb.o ./Core/IntelDecimal/bid128_logb.su ./Core/IntelDecimal/bid128_logbd.cyclo ./Core/IntelDecimal/bid128_logbd.d ./Core/IntelDecimal/bid128_logbd.o ./Core/IntelDecimal/bid128_logbd.su ./Core/IntelDecimal/bid128_lrintd.cyclo ./Core/IntelDecimal/bid128_lrintd.d ./Core/IntelDecimal/bid128_lrintd.o ./Core/IntelDecimal/bid128_lrintd.su ./Core/IntelDecimal/bid128_lround.cyclo ./Core/IntelDecimal/bid128_lround.d ./Core/IntelDecimal/bid128_lround.o ./Core/IntelDecimal/bid128_lround.su ./Core/IntelDecimal/bid128_minmax.cyclo ./Core/IntelDecimal/bid128_minmax.d ./Core/IntelDecimal/bid128_minmax.o ./Core/IntelDecimal/bid128_minmax.su ./Core/IntelDecimal/bid128_modf.cyclo ./Core/IntelDecimal/bid128_modf.d ./Core/IntelDecimal/bid128_modf.o ./Core/IntelDecimal/bid128_modf.su ./Core/IntelDecimal/bid128_mul.cyclo ./Core/IntelDecimal/bid128_mul.d ./Core/IntelDecimal/bid128_mul.o ./Core/IntelDecimal/bid128_mul.su ./Core/IntelDecimal/bid128_nearbyintd.cyclo ./Core/IntelDecimal/bid128_nearbyintd.d ./Core/IntelDecimal/bid128_nearbyintd.o ./Core/IntelDecimal/bid128_nearbyintd.su ./Core/IntelDecimal/bid128_next.cyclo ./Core/IntelDecimal/bid128_next.d
	-$(RM) ./Core/IntelDecimal/bid128_next.o ./Core/IntelDecimal/bid128_next.su ./Core/IntelDecimal/bid128_nexttowardd.cyclo ./Core/IntelDecimal/bid128_nexttowardd.d ./Core/IntelDecimal/bid128_nexttowardd.o ./Core/IntelDecimal/bid128_nexttowardd.su ./Core/IntelDecimal/bid128_noncomp.cyclo ./Core/IntelDecimal/bid128_noncomp.d ./Core/IntelDecimal/bid128_noncomp.o ./Core/IntelDecimal/bid128_noncomp.su ./Core/IntelDecimal/bid128_pow.cyclo ./Core/IntelDecimal/bid128_pow.d ./Core/IntelDecimal/bid128_pow.o ./Core/IntelDecimal/bid128_pow.su ./Core/IntelDecimal/bid128_quantexpd.cyclo ./Core/IntelDecimal/bid128_quantexpd.d ./Core/IntelDecimal/bid128_quantexpd.o ./Core/IntelDecimal/bid128_quantexpd.su ./Core/IntelDecimal/bid128_quantize.cyclo ./Core/IntelDecimal/bid128_quantize.d ./Core/IntelDecimal/bid128_quantize.o ./Core/IntelDecimal/bid128_quantize.su ./Core/IntelDecimal/bid128_rem.cyclo ./Core/IntelDecimal/bid128_rem.d ./Core/IntelDecimal/bid128_rem.o ./Core/IntelDecimal/bid128_rem.su ./Core/IntelDecimal/bid128_round_integral.cyclo ./Core/IntelDecimal/bid128_round_integral.d ./Core/IntelDecimal/bid128_round_integral.o ./Core/IntelDecimal/bid128_round_integral.su ./Core/IntelDecimal/bid128_scalb.cyclo ./Core/IntelDecimal/bid128_scalb.d ./Core/IntelDecimal/bid128_scalb.o ./Core/IntelDecimal/bid128_scalb.su ./Core/IntelDecimal/bid128_scalbl.cyclo ./Core/IntelDecimal/bid128_scalbl.d ./Core/IntelDecimal/bid128_scalbl.o ./Core/IntelDecimal/bid128_scalbl.su ./Core/IntelDecimal/bid128_sin.cyclo ./Core/IntelDecimal/bid128_sin.d ./Core/IntelDecimal/bid128_sin.o ./Core/IntelDecimal/bid128_sin.su ./Core/IntelDecimal/bid128_sinh.cyclo ./Core/IntelDecimal/bid128_sinh.d ./Core/IntelDecimal/bid128_sinh.o ./Core/IntelDecimal/bid128_sinh.su ./Core/IntelDecimal/bid128_sqrt.cyclo ./Core/IntelDecimal/bid128_sqrt.d ./Core/IntelDecimal/bid128_sqrt.o ./Core/IntelDecimal/bid128_sqrt.su ./Core/IntelDecimal/bid128_string.cyclo ./Core/IntelDecimal/bid128_string.d ./Core/IntelDecimal/bid128_string.o ./Core/IntelDecimal/bid128_string.su ./Core/IntelDecimal/bid128_tan.cyclo ./Core/IntelDecimal/bid128_tan.d ./Core/IntelDecimal/bid128_tan.o ./Core/IntelDecimal/bid128_tan.su ./Core/IntelDecimal/bid128_tanh.cyclo ./Core/IntelDecimal/bid128_tanh.d ./Core/IntelDecimal/bid128_tanh.o ./Core/IntelDecimal/bid128_tanh.su ./Core/IntelDecimal/bid128_tgamma.cyclo ./Core/IntelDecimal/bid128_tgamma.d ./Core/IntelDecimal/bid128_tgamma.o ./Core/IntelDecimal/bid128_tgamma.su ./Core/IntelDecimal/bid128_to_int16.cyclo ./Core/IntelDecimal/bid128_to_int16.d ./Core/IntelDecimal/bid128_to_int16.o ./Core/IntelDecimal/bid128_to_int16.su ./Core/IntelDecimal/bid128_to_int32.cyclo ./Core/IntelDecimal/bid128_to_int32.d ./Core/IntelDecimal/bid128_to_int32.o ./Core/IntelDecimal/bid128_to_int32.su ./Core/IntelDecimal/bid128_to_int64.cyclo ./Core/IntelDecimal/bid128_to_int64.d ./Core/IntelDecimal/bid128_to_int64.o ./Core/IntelDecimal/bid128_to_int64.su ./Core/IntelDecimal/bid128_to_int8.cyclo ./Core/IntelDecimal/bid128_to_int8.d ./Core/IntelDecimal/bid128_to_int8.o ./Core/IntelDecimal/bid128_to_int8.su ./Core/IntelDecimal/bid128_to_uint16.cyclo ./Core/IntelDecimal/bid128_to_uint16.d ./Core/IntelDecimal/bid128_to_uint16.o ./Core/IntelDecimal/bid128_to_uint16.su ./Core/IntelDecimal/bid128_to_uint32.cyclo ./Core/IntelDecimal/bid128_to_uint32.d ./Core/IntelDecimal/bid128_to_uint32.o ./Core/IntelDecimal/bid128_to_uint32.su ./Core/IntelDecimal/bid128_to_uint64.cyclo ./Core/IntelDecimal/bid128_to_uint64.d ./Core/IntelDecimal/bid128_to_uint64.o ./Core/IntelDecimal/bid128_to_uint64.su ./Core/IntelDecimal/bid128_to_uint8.cyclo ./Core/IntelDecimal/bid128_to_uint8.d ./Core/IntelDecimal/bid128_to_uint8.o ./Core/IntelDecimal/bid128_to_uint8.su ./Core/IntelDecimal/bid32_acos.cyclo ./Core/IntelDecimal/bid32_acos.d ./Core/IntelDecimal/bid32_acos.o ./Core/IntelDecimal/bid32_acos.su ./Core/IntelDecimal/bid32_acosh.cyclo ./Core/IntelDecimal/bid32_acosh.d ./Core/IntelDecimal/bid32_acosh.o ./Core/IntelDecimal/bid32_acosh.su ./Core/IntelDecimal/bid32_add.cyclo ./Core/IntelDecimal/bid32_add.d ./Core/IntelDecimal/bid32_add.o ./Core/IntelDecimal/bid32_add.su ./Core/IntelDecimal/bid32_asin.cyclo ./Core/IntelDecimal/bid32_asin.d ./Core/IntelDecimal/bid32_asin.o ./Core/IntelDecimal/bid32_asin.su ./Core/IntelDecimal/bid32_asinh.cyclo ./Core/IntelDecimal/bid32_asinh.d ./Core/IntelDecimal/bid32_asinh.o ./Core/IntelDecimal/bid32_asinh.su ./Core/IntelDecimal/bid32_atan.cyclo ./Core/IntelDecimal/bid32_atan.d ./Core/IntelDecimal/bid32_atan.o ./Core/IntelDecimal/bid32_atan.su ./Core/IntelDecimal/bid32_atan2.cyclo ./Core/IntelDecimal/bid32_atan2.d ./Core/IntelDecimal/bid32_atan2.o ./Core/IntelDecimal/bid32_atan2.su ./Core/IntelDecimal/bid32_atanh.cyclo ./Core/IntelDecimal/bid32_atanh.d ./Core/IntelDecimal/bid32_atanh.o ./Core/IntelDecimal/bid32_atanh.su ./Core/IntelDecimal/bid32_cbrt.cyclo ./Core/IntelDecimal/bid32_cbrt.d ./Core/IntelDecimal/bid32_cbrt.o ./Core/IntelDecimal/bid32_cbrt.su ./Core/IntelDecimal/bid32_compare.cyclo ./Core/IntelDecimal/bid32_compare.d ./Core/IntelDecimal/bid32_compare.o ./Core/IntelDecimal/bid32_compare.su ./Core/IntelDecimal/bid32_cos.cyclo ./Core/IntelDecimal/bid32_cos.d ./Core/IntelDecimal/bid32_cos.o ./Core/IntelDecimal/bid32_cos.su ./Core/IntelDecimal/bid32_cosh.cyclo ./Core/IntelDecimal/bid32_cosh.d ./Core/IntelDecimal/bid32_cosh.o ./Core/IntelDecimal/bid32_cosh.su ./Core/IntelDecimal/bid32_div.cyclo ./Core/IntelDecimal/bid32_div.d ./Core/IntelDecimal/bid32_div.o ./Core/IntelDecimal/bid32_div.su ./Core/IntelDecimal/bid32_erf.cyclo ./Core/IntelDecimal/bid32_erf.d ./Core/IntelDecimal/bid32_erf.o ./Core/IntelDecimal/bid32_erf.su ./Core/IntelDecimal/bid32_erfc.cyclo ./Core/IntelDecimal/bid32_erfc.d ./Core/IntelDecimal/bid32_erfc.o ./Core/IntelDecimal/bid32_erfc.su ./Core/IntelDecimal/bid32_exp.cyclo ./Core/IntelDecimal/bid32_exp.d ./Core/IntelDecimal/bid32_exp.o ./Core/IntelDecimal/bid32_exp.su ./Core/IntelDecimal/bid32_exp10.cyclo ./Core/IntelDecimal/bid32_exp10.d
	-$(RM) ./Core/IntelDecimal/bid32_exp10.o ./Core/IntelDecimal/bid32_exp10.su ./Core/IntelDecimal/bid32_exp2.cyclo ./Core/IntelDecimal/bid32_exp2.d ./Core/IntelDecimal/bid32_exp2.o ./Core/IntelDecimal/bid32_exp2.su ./Core/IntelDecimal/bid32_expm1.cyclo ./Core/IntelDecimal/bid32_expm1.d ./Core/IntelDecimal/bid32_expm1.o ./Core/IntelDecimal/bid32_expm1.su ./Core/IntelDecimal/bid32_fdimd.cyclo ./Core/IntelDecimal/bid32_fdimd.d ./Core/IntelDecimal/bid32_fdimd.o ./Core/IntelDecimal/bid32_fdimd.su ./Core/IntelDecimal/bid32_fma.cyclo ./Core/IntelDecimal/bid32_fma.d ./Core/IntelDecimal/bid32_fma.o ./Core/IntelDecimal/bid32_fma.su ./Core/IntelDecimal/bid32_fmod.cyclo ./Core/IntelDecimal/bid32_fmod.d ./Core/IntelDecimal/bid32_fmod.o ./Core/IntelDecimal/bid32_fmod.su ./Core/IntelDecimal/bid32_frexp.cyclo ./Core/IntelDecimal/bid32_frexp.d ./Core/IntelDecimal/bid32_frexp.o ./Core/IntelDecimal/bid32_frexp.su ./Core/IntelDecimal/bid32_hypot.cyclo ./Core/IntelDecimal/bid32_hypot.d ./Core/IntelDecimal/bid32_hypot.o ./Core/IntelDecimal/bid32_hypot.su ./Core/IntelDecimal/bid32_ldexp.cyclo ./Core/IntelDecimal/bid32_ldexp.d ./Core/IntelDecimal/bid32_ldexp.o ./Core/IntelDecimal/bid32_ldexp.su ./Core/IntelDecimal/bid32_lgamma.cyclo ./Core/IntelDecimal/bid32_lgamma.d ./Core/IntelDecimal/bid32_lgamma.o ./Core/IntelDecimal/bid32_lgamma.su ./Core/IntelDecimal/bid32_llrintd.cyclo ./Core/IntelDecimal/bid32_llrintd.d ./Core/IntelDecimal/bid32_llrintd.o ./Core/IntelDecimal/bid32_llrintd.su ./Core/IntelDecimal/bid32_log.cyclo ./Core/IntelDecimal/bid32_log.d ./Core/IntelDecimal/bid32_log.o ./Core/IntelDecimal/bid32_log.su ./Core/IntelDecimal/bid32_log10.cyclo ./Core/IntelDecimal/bid32_log10.d ./Core/IntelDecimal/bid32_log10.o ./Core/IntelDecimal/bid32_log10.su ./Core/IntelDecimal/bid32_log1p.cyclo ./Core/IntelDecimal/bid32_log1p.d ./Core/IntelDecimal/bid32_log1p.o ./Core/IntelDecimal/bid32_log1p.su ./Core/IntelDecimal/bid32_log2.cyclo ./Core/IntelDecimal/bid32_log2.d ./Core/IntelDecimal/bid32_log2.o ./Core/IntelDecimal/bid32_log2.su ./Core/IntelDecimal/bid32_logb.cyclo ./Core/IntelDecimal/bid32_logb.d ./Core/IntelDecimal/bid32_logb.o ./Core/IntelDecimal/bid32_logb.su ./Core/IntelDecimal/bid32_logbd.cyclo ./Core/IntelDecimal/bid32_logbd.d ./Core/IntelDecimal/bid32_logbd.o ./Core/IntelDecimal/bid32_logbd.su ./Core/IntelDecimal/bid32_lrintd.cyclo ./Core/IntelDecimal/bid32_lrintd.d ./Core/IntelDecimal/bid32_lrintd.o ./Core/IntelDecimal/bid32_lrintd.su ./Core/IntelDecimal/bid32_lround.cyclo ./Core/IntelDecimal/bid32_lround.d ./Core/IntelDecimal/bid32_lround.o ./Core/IntelDecimal/bid32_lround.su ./Core/IntelDecimal/bid32_minmax.cyclo ./Core/IntelDecimal/bid32_minmax.d ./Core/IntelDecimal/bid32_minmax.o ./Core/IntelDecimal/bid32_minmax.su ./Core/IntelDecimal/bid32_modf.cyclo ./Core/IntelDecimal/bid32_modf.d ./Core/IntelDecimal/bid32_modf.o ./Core/IntelDecimal/bid32_modf.su ./Core/IntelDecimal/bid32_mul.cyclo ./Core/IntelDecimal/bid32_mul.d ./Core/IntelDecimal/bid32_mul.o ./Core/IntelDecimal/bid32_mul.su ./Core/IntelDecimal/bid32_nearbyintd.cyclo ./Core/IntelDecimal/bid32_nearbyintd.d ./Core/IntelDecimal/bid32_nearbyintd.o ./Core/IntelDecimal/bid32_nearbyintd.su ./Core/IntelDecimal/bid32_next.cyclo ./Core/IntelDecimal/bid32_next.d ./Core/IntelDecimal/bid32_next.o ./Core/IntelDecimal/bid32_next.su ./Core/IntelDecimal/bid32_nexttowardd.cyclo ./Core/IntelDecimal/bid32_nexttowardd.d ./Core/IntelDecimal/bid32_nexttowardd.o ./Core/IntelDecimal/bid32_nexttowardd.su ./Core/IntelDecimal/bid32_noncomp.cyclo ./Core/IntelDecimal/bid32_noncomp.d ./Core/IntelDecimal/bid32_noncomp.o ./Core/IntelDecimal/bid32_noncomp.su ./Core/IntelDecimal/bid32_pow.cyclo ./Core/IntelDecimal/bid32_pow.d ./Core/IntelDecimal/bid32_pow.o ./Core/IntelDecimal/bid32_pow.su ./Core/IntelDecimal/bid32_quantexpd.cyclo ./Core/IntelDecimal/bid32_quantexpd.d ./Core/IntelDecimal/bid32_quantexpd.o ./Core/IntelDecimal/bid32_quantexpd.su ./Core/IntelDecimal/bid32_quantize.cyclo ./Core/IntelDecimal/bid32_quantize.d ./Core/IntelDecimal/bid32_quantize.o ./Core/IntelDecimal/bid32_quantize.su ./Core/IntelDecimal/bid32_rem.cyclo ./Core/IntelDecimal/bid32_rem.d ./Core/IntelDecimal/bid32_rem.o ./Core/IntelDecimal/bid32_rem.su ./Core/IntelDecimal/bid32_round_integral.cyclo ./Core/IntelDecimal/bid32_round_integral.d ./Core/IntelDecimal/bid32_round_integral.o ./Core/IntelDecimal/bid32_round_integral.su ./Core/IntelDecimal/bid32_scalb.cyclo ./Core/IntelDecimal/bid32_scalb.d ./Core/IntelDecimal/bid32_scalb.o ./Core/IntelDecimal/bid32_scalb.su ./Core/IntelDecimal/bid32_scalbl.cyclo ./Core/IntelDecimal/bid32_scalbl.d ./Core/IntelDecimal/bid32_scalbl.o ./Core/IntelDecimal/bid32_scalbl.su ./Core/IntelDecimal/bid32_sin.cyclo ./Core/IntelDecimal/bid32_sin.d ./Core/IntelDecimal/bid32_sin.o ./Core/IntelDecimal/bid32_sin.su ./Core/IntelDecimal/bid32_sinh.cyclo ./Core/IntelDecimal/bid32_sinh.d ./Core/IntelDecimal/bid32_sinh.o ./Core/IntelDecimal/bid32_sinh.su ./Core/IntelDecimal/bid32_sqrt.cyclo ./Core/IntelDecimal/bid32_sqrt.d ./Core/IntelDecimal/bid32_sqrt.o ./Core/IntelDecimal/bid32_sqrt.su ./Core/IntelDecimal/bid32_string.cyclo ./Core/IntelDecimal/bid32_string.d ./Core/IntelDecimal/bid32_string.o ./Core/IntelDecimal/bid32_string.su ./Core/IntelDecimal/bid32_sub.cyclo ./Core/IntelDecimal/bid32_sub.d ./Core/IntelDecimal/bid32_sub.o ./Core/IntelDecimal/bid32_sub.su ./Core/IntelDecimal/bid32_tan.cyclo ./Core/IntelDecimal/bid32_tan.d ./Core/IntelDecimal/bid32_tan.o ./Core/IntelDecimal/bid32_tan.su ./Core/IntelDecimal/bid32_tanh.cyclo ./Core/IntelDecimal/bid32_tanh.d ./Core/IntelDecimal/bid32_tanh.o ./Core/IntelDecimal/bid32_tanh.su ./Core/IntelDecimal/bid32_tgamma.cyclo ./Core/IntelDecimal/bid32_tgamma.d ./Core/IntelDecimal/bid32_tgamma.o ./Core/IntelDecimal/bid32_tgamma.su ./Core/IntelDecimal/bid32_to_bid128.cyclo ./Core/IntelDecimal/bid32_to_bid128.d ./Core/IntelDecimal/bid32_to_bid128.o ./Core/IntelDecimal/bid32_to_bid128.su ./Core/IntelDecimal/bid32_to_bid64.cyclo
	-$(RM) ./Core/IntelDecimal/bid32_to_bid64.d ./Core/IntelDecimal/bid32_to_bid64.o ./Core/IntelDecimal/bid32_to_bid64.su ./Core/IntelDecimal/bid32_to_int16.cyclo ./Core/IntelDecimal/bid32_to_int16.d ./Core/IntelDecimal/bid32_to_int16.o ./Core/IntelDecimal/bid32_to_int16.su ./Core/IntelDecimal/bid32_to_int32.cyclo ./Core/IntelDecimal/bid32_to_int32.d ./Core/IntelDecimal/bid32_to_int32.o ./Core/IntelDecimal/bid32_to_int32.su ./Core/IntelDecimal/bid32_to_int64.cyclo ./Core/IntelDecimal/bid32_to_int64.d ./Core/IntelDecimal/bid32_to_int64.o ./Core/IntelDecimal/bid32_to_int64.su ./Core/IntelDecimal/bid32_to_int8.cyclo ./Core/IntelDecimal/bid32_to_int8.d ./Core/IntelDecimal/bid32_to_int8.o ./Core/IntelDecimal/bid32_to_int8.su ./Core/IntelDecimal/bid32_to_uint16.cyclo ./Core/IntelDecimal/bid32_to_uint16.d ./Core/IntelDecimal/bid32_to_uint16.o ./Core/IntelDecimal/bid32_to_uint16.su ./Core/IntelDecimal/bid32_to_uint32.cyclo ./Core/IntelDecimal/bid32_to_uint32.d ./Core/IntelDecimal/bid32_to_uint32.o ./Core/IntelDecimal/bid32_to_uint32.su ./Core/IntelDecimal/bid32_to_uint64.cyclo ./Core/IntelDecimal/bid32_to_uint64.d ./Core/IntelDecimal/bid32_to_uint64.o ./Core/IntelDecimal/bid32_to_uint64.su ./Core/IntelDecimal/bid32_to_uint8.cyclo ./Core/IntelDecimal/bid32_to_uint8.d ./Core/IntelDecimal/bid32_to_uint8.o ./Core/IntelDecimal/bid32_to_uint8.su ./Core/IntelDecimal/bid64_acos.cyclo ./Core/IntelDecimal/bid64_acos.d ./Core/IntelDecimal/bid64_acos.o ./Core/IntelDecimal/bid64_acos.su ./Core/IntelDecimal/bid64_acosh.cyclo ./Core/IntelDecimal/bid64_acosh.d ./Core/IntelDecimal/bid64_acosh.o ./Core/IntelDecimal/bid64_acosh.su ./Core/IntelDecimal/bid64_add.cyclo ./Core/IntelDecimal/bid64_add.d ./Core/IntelDecimal/bid64_add.o ./Core/IntelDecimal/bid64_add.su ./Core/IntelDecimal/bid64_asin.cyclo ./Core/IntelDecimal/bid64_asin.d ./Core/IntelDecimal/bid64_asin.o ./Core/IntelDecimal/bid64_asin.su ./Core/IntelDecimal/bid64_asinh.cyclo ./Core/IntelDecimal/bid64_asinh.d ./Core/IntelDecimal/bid64_asinh.o ./Core/IntelDecimal/bid64_asinh.su ./Core/IntelDecimal/bid64_atan.cyclo ./Core/IntelDecimal/bid64_atan.d ./Core/IntelDecimal/bid64_atan.o ./Core/IntelDecimal/bid64_atan.su ./Core/IntelDecimal/bid64_atan2.cyclo ./Core/IntelDecimal/bid64_atan2.d ./Core/IntelDecimal/bid64_atan2.o ./Core/IntelDecimal/bid64_atan2.su ./Core/IntelDecimal/bid64_atanh.cyclo ./Core/IntelDecimal/bid64_atanh.d ./Core/IntelDecimal/bid64_atanh.o ./Core/IntelDecimal/bid64_atanh.su ./Core/IntelDecimal/bid64_cbrt.cyclo ./Core/IntelDecimal/bid64_cbrt.d ./Core/IntelDecimal/bid64_cbrt.o ./Core/IntelDecimal/bid64_cbrt.su ./Core/IntelDecimal/bid64_compare.cyclo ./Core/IntelDecimal/bid64_compare.d ./Core/IntelDecimal/bid64_compare.o ./Core/IntelDecimal/bid64_compare.su ./Core/IntelDecimal/bid64_cos.cyclo ./Core/IntelDecimal/bid64_cos.d ./Core/IntelDecimal/bid64_cos.o ./Core/IntelDecimal/bid64_cos.su ./Core/IntelDecimal/bid64_cosh.cyclo ./Core/IntelDecimal/bid64_cosh.d ./Core/IntelDecimal/bid64_cosh.o ./Core/IntelDecimal/bid64_cosh.su ./Core/IntelDecimal/bid64_div.cyclo ./Core/IntelDecimal/bid64_div.d ./Core/IntelDecimal/bid64_div.o ./Core/IntelDecimal/bid64_div.su ./Core/IntelDecimal/bid64_erf.cyclo ./Core/IntelDecimal/bid64_erf.d ./Core/IntelDecimal/bid64_erf.o ./Core/IntelDecimal/bid64_erf.su ./Core/IntelDecimal/bid64_erfc.cyclo ./Core/IntelDecimal/bid64_erfc.d ./Core/IntelDecimal/bid64_erfc.o ./Core/IntelDecimal/bid64_erfc.su ./Core/IntelDecimal/bid64_exp.cyclo ./Core/IntelDecimal/bid64_exp.d ./Core/IntelDecimal/bid64_exp.o ./Core/IntelDecimal/bid64_exp.su ./Core/IntelDecimal/bid64_exp10.cyclo ./Core/IntelDecimal/bid64_exp10.d ./Core/IntelDecimal/bid64_exp10.o ./Core/IntelDecimal/bid64_exp10.su ./Core/IntelDecimal/bid64_exp2.cyclo ./Core/IntelDecimal/bid64_exp2.d ./Core/IntelDecimal/bid64_exp2.o ./Core/IntelDecimal/bid64_exp2.su ./Core/IntelDecimal/bid64_expm1.cyclo ./Core/IntelDecimal/bid64_expm1.d ./Core/IntelDecimal/bid64_expm1.o ./Core/IntelDecimal/bid64_expm1.su ./Core/IntelDecimal/bid64_fdimd.cyclo ./Core/IntelDecimal/bid64_fdimd.d ./Core/IntelDecimal/bid64_fdimd.o ./Core/IntelDecimal/bid64_fdimd.su ./Core/IntelDecimal/bid64_fma.cyclo ./Core/IntelDecimal/bid64_fma.d ./Core/IntelDecimal/bid64_fma.o ./Core/IntelDecimal/bid64_fma.su ./Core/IntelDecimal/bid64_fmod.cyclo ./Core/IntelDecimal/bid64_fmod.d ./Core/IntelDecimal/bid64_fmod.o ./Core/IntelDecimal/bid64_fmod.su ./Core/IntelDecimal/bid64_frexp.cyclo ./Core/IntelDecimal/bid64_frexp.d ./Core/IntelDecimal/bid64_frexp.o ./Core/IntelDecimal/bid64_frexp.su ./Core/IntelDecimal/bid64_hypot.cyclo ./Core/IntelDecimal/bid64_hypot.d ./Core/IntelDecimal/bid64_hypot.o ./Core/IntelDecimal/bid64_hypot.su ./Core/IntelDecimal/bid64_ldexp.cyclo ./Core/IntelDecimal/bid64_ldexp.d ./Core/IntelDecimal/bid64_ldexp.o ./Core/IntelDecimal/bid64_ldexp.su ./Core/IntelDecimal/bid64_lgamma.cyclo ./Core/IntelDecimal/bid64_lgamma.d ./Core/IntelDecimal/bid64_lgamma.o ./Core/IntelDecimal/bid64_lgamma.su ./Core/IntelDecimal/bid64_llrintd.cyclo ./Core/IntelDecimal/bid64_llrintd.d ./Core/IntelDecimal/bid64_llrintd.o ./Core/IntelDecimal/bid64_llrintd.su ./Core/IntelDecimal/bid64_log.cyclo ./Core/IntelDecimal/bid64_log.d ./Core/IntelDecimal/bid64_log.o ./Core/IntelDecimal/bid64_log.su ./Core/IntelDecimal/bid64_log10.cyclo ./Core/IntelDecimal/bid64_log10.d ./Core/IntelDecimal/bid64_log10.o ./Core/IntelDecimal/bid64_log10.su ./Core/IntelDecimal/bid64_log1p.cyclo ./Core/IntelDecimal/bid64_log1p.d ./Core/IntelDecimal/bid64_log1p.o ./Core/IntelDecimal/bid64_log1p.su ./Core/IntelDecimal/bid64_log2.cyclo ./Core/IntelDecimal/bid64_log2.d ./Core/IntelDecimal/bid64_log2.o ./Core/IntelDecimal/bid64_log2.su ./Core/IntelDecimal/bid64_logb.cyclo ./Core/IntelDecimal/bid64_logb.d ./Core/IntelDecimal/bid64_logb.o ./Core/IntelDecimal/bid64_logb.su ./Core/IntelDecimal/bid64_logbd.cyclo ./Core/IntelDecimal/bid64_logbd.d ./Core/IntelDecimal/bid64_logbd.o ./Core/IntelDecimal/bid64_logbd.su ./Core/IntelDecimal/bid64_lrintd.cyclo
	-$(RM) ./Core/IntelDecimal/bid64_lrintd.d ./Core/IntelDecimal/bid64_lrintd.o ./Core/IntelDecimal/bid64_lrintd.su ./Core/IntelDecimal/bid64_lround.cyclo ./Core/IntelDecimal/bid64_lround.d ./Core/IntelDecimal/bid64_lround.o ./Core/IntelDecimal/bid64_lround.su ./Core/IntelDecimal/bid64_minmax.cyclo ./Core/IntelDecimal/bid64_minmax.d ./Core/IntelDecimal/bid64_minmax.o ./Core/IntelDecimal/bid64_minmax.su ./Core/IntelDecimal/bid64_modf.cyclo ./Core/IntelDecimal/bid64_modf.d ./Core/IntelDecimal/bid64_modf.o ./Core/IntelDecimal/bid64_modf.su ./Core/IntelDecimal/bid64_mul.cyclo ./Core/IntelDecimal/bid64_mul.d ./Core/IntelDecimal/bid64_mul.o ./Core/IntelDecimal/bid64_mul.su ./Core/IntelDecimal/bid64_nearbyintd.cyclo ./Core/IntelDecimal/bid64_nearbyintd.d ./Core/IntelDecimal/bid64_nearbyintd.o ./Core/IntelDecimal/bid64_nearbyintd.su ./Core/IntelDecimal/bid64_next.cyclo ./Core/IntelDecimal/bid64_next.d ./Core/IntelDecimal/bid64_next.o ./Core/IntelDecimal/bid64_next.su ./Core/IntelDecimal/bid64_nexttowardd.cyclo ./Core/IntelDecimal/bid64_nexttowardd.d ./Core/IntelDecimal/bid64_nexttowardd.o ./Core/IntelDecimal/bid64_nexttowardd.su ./Core/IntelDecimal/bid64_noncomp.cyclo ./Core/IntelDecimal/bid64_noncomp.d ./Core/IntelDecimal/bid64_noncomp.o ./Core/IntelDecimal/bid64_noncomp.su ./Core/IntelDecimal/bid64_pow.cyclo ./Core/IntelDecimal/bid64_pow.d ./Core/IntelDecimal/bid64_pow.o ./Core/IntelDecimal/bid64_pow.su ./Core/IntelDecimal/bid64_quantexpd.cyclo ./Core/IntelDecimal/bid64_quantexpd.d ./Core/IntelDecimal/bid64_quantexpd.o ./Core/IntelDecimal/bid64_quantexpd.su ./Core/IntelDecimal/bid64_quantize.cyclo ./Core/IntelDecimal/bid64_quantize.d ./Core/IntelDecimal/bid64_quantize.o ./Core/IntelDecimal/bid64_quantize.su ./Core/IntelDecimal/bid64_rem.cyclo ./Core/IntelDecimal/bid64_rem.d ./Core/IntelDecimal/bid64_rem.o ./Core/IntelDecimal/bid64_rem.su ./Core/IntelDecimal/bid64_round_integral.cyclo ./Core/IntelDecimal/bid64_round_integral.d ./Core/IntelDecimal/bid64_round_integral.o ./Core/IntelDecimal/bid64_round_integral.su ./Core/IntelDecimal/bid64_scalb.cyclo ./Core/IntelDecimal/bid64_scalb.d ./Core/IntelDecimal/bid64_scalb.o ./Core/IntelDecimal/bid64_scalb.su ./Core/IntelDecimal/bid64_scalbl.cyclo ./Core/IntelDecimal/bid64_scalbl.d ./Core/IntelDecimal/bid64_scalbl.o ./Core/IntelDecimal/bid64_scalbl.su ./Core/IntelDecimal/bid64_sin.cyclo ./Core/IntelDecimal/bid64_sin.d ./Core/IntelDecimal/bid64_sin.o ./Core/IntelDecimal/bid64_sin.su ./Core/IntelDecimal/bid64_sinh.cyclo ./Core/IntelDecimal/bid64_sinh.d ./Core/IntelDecimal/bid64_sinh.o ./Core/IntelDecimal/bid64_sinh.su ./Core/IntelDecimal/bid64_sqrt.cyclo ./Core/IntelDecimal/bid64_sqrt.d ./Core/IntelDecimal/bid64_sqrt.o ./Core/IntelDecimal/bid64_sqrt.su ./Core/IntelDecimal/bid64_string.cyclo ./Core/IntelDecimal/bid64_string.d ./Core/IntelDecimal/bid64_string.o ./Core/IntelDecimal/bid64_string.su ./Core/IntelDecimal/bid64_tan.cyclo ./Core/IntelDecimal/bid64_tan.d ./Core/IntelDecimal/bid64_tan.o ./Core/IntelDecimal/bid64_tan.su ./Core/IntelDecimal/bid64_tanh.cyclo ./Core/IntelDecimal/bid64_tanh.d ./Core/IntelDecimal/bid64_tanh.o ./Core/IntelDecimal/bid64_tanh.su ./Core/IntelDecimal/bid64_tgamma.cyclo ./Core/IntelDecimal/bid64_tgamma.d ./Core/IntelDecimal/bid64_tgamma.o ./Core/IntelDecimal/bid64_tgamma.su ./Core/IntelDecimal/bid64_to_bid128.cyclo ./Core/IntelDecimal/bid64_to_bid128.d ./Core/IntelDecimal/bid64_to_bid128.o ./Core/IntelDecimal/bid64_to_bid128.su ./Core/IntelDecimal/bid64_to_int16.cyclo ./Core/IntelDecimal/bid64_to_int16.d ./Core/IntelDecimal/bid64_to_int16.o ./Core/IntelDecimal/bid64_to_int16.su ./Core/IntelDecimal/bid64_to_int32.cyclo ./Core/IntelDecimal/bid64_to_int32.d ./Core/IntelDecimal/bid64_to_int32.o ./Core/IntelDecimal/bid64_to_int32.su ./Core/IntelDecimal/bid64_to_int64.cyclo ./Core/IntelDecimal/bid64_to_int64.d ./Core/IntelDecimal/bid64_to_int64.o ./Core/IntelDecimal/bid64_to_int64.su ./Core/IntelDecimal/bid64_to_int8.cyclo ./Core/IntelDecimal/bid64_to_int8.d ./Core/IntelDecimal/bid64_to_int8.o ./Core/IntelDecimal/bid64_to_int8.su ./Core/IntelDecimal/bid64_to_uint16.cyclo ./Core/IntelDecimal/bid64_to_uint16.d ./Core/IntelDecimal/bid64_to_uint16.o ./Core/IntelDecimal/bid64_to_uint16.su ./Core/IntelDecimal/bid64_to_uint32.cyclo ./Core/IntelDecimal/bid64_to_uint32.d ./Core/IntelDecimal/bid64_to_uint32.o ./Core/IntelDecimal/bid64_to_uint32.su ./Core/IntelDecimal/bid64_to_uint64.cyclo ./Core/IntelDecimal/bid64_to_uint64.d ./Core/IntelDecimal/bid64_to_uint64.o ./Core/IntelDecimal/bid64_to_uint64.su ./Core/IntelDecimal/bid64_to_uint8.cyclo ./Core/IntelDecimal/bid64_to_uint8.d ./Core/IntelDecimal/bid64_to_uint8.o ./Core/IntelDecimal/bid64_to_uint8.su ./Core/IntelDecimal/bid_binarydecimal.cyclo ./Core/IntelDecimal/bid_binarydecimal.d ./Core/IntelDecimal/bid_binarydecimal.o ./Core/IntelDecimal/bid_binarydecimal.su ./Core/IntelDecimal/bid_convert_data.cyclo ./Core/IntelDecimal/bid_convert_data.d ./Core/IntelDecimal/bid_convert_data.o ./Core/IntelDecimal/bid_convert_data.su ./Core/IntelDecimal/bid_decimal_data.cyclo ./Core/IntelDecimal/bid_decimal_data.d ./Core/IntelDecimal/bid_decimal_data.o ./Core/IntelDecimal/bid_decimal_data.su ./Core/IntelDecimal/bid_decimal_globals.cyclo ./Core/IntelDecimal/bid_decimal_globals.d ./Core/IntelDecimal/bid_decimal_globals.o ./Core/IntelDecimal/bid_decimal_globals.su ./Core/IntelDecimal/bid_dpd.cyclo ./Core/IntelDecimal/bid_dpd.d ./Core/IntelDecimal/bid_dpd.o ./Core/IntelDecimal/bid_dpd.su ./Core/IntelDecimal/bid_feclearexcept.cyclo ./Core/IntelDecimal/bid_feclearexcept.d ./Core/IntelDecimal/bid_feclearexcept.o ./Core/IntelDecimal/bid_feclearexcept.su ./Core/IntelDecimal/bid_fegetexceptflag.cyclo ./Core/IntelDecimal/bid_fegetexceptflag.d ./Core/IntelDecimal/bid_fegetexceptflag.o ./Core/IntelDecimal/bid_fegetexceptflag.su ./Core/IntelDecimal/bid_feraiseexcept.cyclo ./Core/IntelDecimal/bid_feraiseexcept.d ./Core/IntelDecimal/bid_feraiseexcept.o ./Core/IntelDecimal/bid_feraiseexcept.su
	-$(RM) ./Core/IntelDecimal/bid_fesetexceptflag.cyclo ./Core/IntelDecimal/bid_fesetexceptflag.d ./Core/IntelDecimal/bid_fesetexceptflag.o ./Core/IntelDecimal/bid_fesetexceptflag.su ./Core/IntelDecimal/bid_fetestexcept.cyclo ./Core/IntelDecimal/bid_fetestexcept.d ./Core/IntelDecimal/bid_fetestexcept.o ./Core/IntelDecimal/bid_fetestexcept.su ./Core/IntelDecimal/bid_flag_operations.cyclo ./Core/IntelDecimal/bid_flag_operations.d ./Core/IntelDecimal/bid_flag_operations.o ./Core/IntelDecimal/bid_flag_operations.su ./Core/IntelDecimal/bid_from_int.cyclo ./Core/IntelDecimal/bid_from_int.d ./Core/IntelDecimal/bid_from_int.o ./Core/IntelDecimal/bid_from_int.su ./Core/IntelDecimal/bid_round.cyclo ./Core/IntelDecimal/bid_round.d ./Core/IntelDecimal/bid_round.o ./Core/IntelDecimal/bid_round.su ./Core/IntelDecimal/strtod128.cyclo ./Core/IntelDecimal/strtod128.d ./Core/IntelDecimal/strtod128.o ./Core/IntelDecimal/strtod128.su ./Core/IntelDecimal/strtod32.cyclo ./Core/IntelDecimal/strtod32.d ./Core/IntelDecimal/strtod32.o ./Core/IntelDecimal/strtod32.su ./Core/IntelDecimal/strtod64.cyclo ./Core/IntelDecimal/strtod64.d ./Core/IntelDecimal/strtod64.o ./Core/IntelDecimal/strtod64.su ./Core/IntelDecimal/wcstod128.cyclo ./Core/IntelDecimal/wcstod128.d ./Core/IntelDecimal/wcstod128.o ./Core/IntelDecimal/wcstod128.su ./Core/IntelDecimal/wcstod32.cyclo ./Core/IntelDecimal/wcstod32.d ./Core/IntelDecimal/wcstod32.o ./Core/IntelDecimal/wcstod32.su ./Core/IntelDecimal/wcstod64.cyclo ./Core/IntelDecimal/wcstod64.d ./Core/IntelDecimal/wcstod64.o ./Core/IntelDecimal/wcstod64.su

.PHONY: clean-Core-2f-IntelDecimal

